console.log('hello world');
var h1 = document.querySelector('h1');
console.log('h1', h1);
console.dir(h1);
var idExplanation = document.querySelector('#explanation');
console.log('idExplanation', idExplanation);
console.dir(idExplanation);
var hint = document.querySelector('.hint');
console.log('.hint', hint);
console.dir(hint);
var p = document.querySelectorAll('p');
console.log('p', p);
var exlink = document.querySelectorAll('.example-link');
console.log('exlink', exlink);
